# Generated by Django 3.2.3 on 2021-05-23 13:32

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210523_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='position',
            field=models.ForeignKey(on_delete=models.SET(User.models.set_position_default), related_name='userinfo_position', related_query_name='position_userinfo', to='User.position', verbose_name='Staff Position'),
        ),
    ]
