# Generated by Django 3.2.3 on 2021-05-23 12:53

import Product.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='created_by',
            field=models.ForeignKey(on_delete=models.SET(Product.models.get_sentinel_user), related_name='supplier_user', related_query_name='user_supplier', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_product', related_query_name='product_stock', to='Product.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='created_by',
            field=models.ForeignKey(on_delete=models.SET(Product.models.get_sentinel_user), related_name='productimage_user', related_query_name='user_productimage', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productimage_product', related_query_name='product_productimage', to='Product.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(on_delete=models.SET(Product.models.get_sentinel_user), related_name='product_user', related_query_name='user_product', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_supplier', related_query_name='supplier_product', to='Product.supplier', verbose_name='Product Supplier'),
        ),
    ]
