# Generated by Django 3.2.3 on 2021-05-23 13:32

import Product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20210523_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=Product.models.image_directory_path, verbose_name='Product Image'),
        ),
    ]
